config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'events#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  post 'attendances', to: 'attendances#attend_event'
  delete 'attendances', to: 'attendances#leave_event'

  resources :users
  resources :events
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
# frozen_string_literal: true

class Attendance < ApplicationRecord
  belongs_to :attended_event, class_name: 'Event'
  belongs_to :attendee, class_name: 'User'
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates :creator_id, presence: true
  validates :title, presence: true
  # validates :location, presence: true
  validates :date, presence: true
  validates :description, presence: true

  belongs_to :creator, class_name: 'User'

  has_many :attendances, class_name: 'Attendance',
                         foreign_key: :attended_event_id,
                         dependent: :destroy

  has_many :attendees, through: :attendances, source: :attendee

  scope :past, lambda {
                 where('date < ?', DateTime.current)
                   .order(date: :desc)
               }

  scope :upcoming, lambda {
                     where('date >= ?', DateTime.current)
                       .order(date: :asc)
                   }

  def attendee?(user)
    attendees.include? user
  end

  def upcoming?
    date&.future?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save :downcase_email
  has_many :creator_events, foreign_key: 'creator_id', class_name: 'Event'

  has_many :attendances, class_name: 'Attendance',
                         foreign_key: :attendee_id,
                         dependent: :destroy

  has_many :attended_events, through: :attendances, source: :attended_event

  validates :username, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  def attend(event)
    attended_events.push event
  end

  def leave(event)
    attended_events.delete event
  end

  def attended_event?(event)
    attended_events.include? event
  end

  def creator_event?(event)
    creator_events.include? event
  end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      flash[:danger] = 'Please log in first'
      redirect_to login_url
    end
  end
end

app/controllers/attendances_controller.rb
# frozen_string_literal: true

class AttendancesController < ApplicationController
  before_action :logged_in_user

  def attend_event
    @event = Event.find(params[:event_id])
    current_user.attend @event
    flash[:success] = 'Successfuly added to attended events!'
    redirect_back(fallback_location: @event)
  end

  def leave_event
    @event = Event.find(params[:event_id])
    current_user.leave @event
    flash[:success] = 'Successfuly left the event!'
    redirect_back(fallback_location: @event)
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :logged_in_user, only: %i[new create destroy]
  before_action :correct_user, only: [:destroy]

  def new
    @event = current_user.creator_events.build
  end

  def index
    @events = Event.paginate(page: params[:page])
    @upcoming = @events.upcoming
    @past = @events.past
  end

  def create
    @event = current_user.creator_events.build(events_params)
    redirect_to root_url if @event.save
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:success] = 'Event deleted successfully'
    redirect_back(fallback_location: current_user)
  end

  private

  def events_params
    params.require(:event).permit(:title, :date, :description)
  end

  def correct_user
    @event = current_user.creator_events.find_by(id: params[:id])
    redirect_to root_url if @event.nil?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Wrong email or password'
      render 'new'
    end
  end

  def destroy
    signout if logged_in?
    flash.now[:warning] = 'You have signed out!'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      flash[:danger] = 'Failed to create an event'
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @my_events = @user.creator_events.paginate(page: params[:page])
    @attended_events = @user.attended_events.paginate(page: params[:page])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/attendances_helper.rb
# frozen_string_literal: true

module AttendancesHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current loggen-in user (if any)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the user
  def signout
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/events/_event.html.erb
<% @event = event %>
<% @user = @event.creator%>
<% if @event %>
   <div class=" event media border p-3">
        <div class="media-body">
            <p class="creator">
                By: <%= link_to @event.creator.username, user_path(@user) %> 
                <span class="timestamp" ><%= time_ago_in_words(@event.created_at) %> ago.</span>
            </p>
            <p class="title">
                <strong><%= link_to @event.title, event_path(@event) %></strong>
            </p>
            <p class="date">
                <strong>On:</strong> <%= @event.date %>
            </p>
        
            <%= link_to event_path(@event), class: "card-overlay", data: { confirm: "Move to : #{@event.title}?" } do %>
                <%= render 'shared/functions', event: @event %>
            <% end %>
        </div>
    </div> 
<% end %>

app/views/events/index.html.erb
<div class="jumbotron">
    <h2> Welcome to Happening </h2>
    <p> This is where you create your own events and invite only specified people to attend </p>
    <% if logged_in? %>
        <%= link_to "Add Event", new_event_url, class: 'btn btn-primary' %>

    <% else %>
        <%= link_to "Sign In Now To Get Started", login_path, class: 'btn btn-primary' %>   
    <% end %>
</div>

<% if logged_in? %>
    <h4> Events </h4>
    <hr>

<% if @events.any? %>
<div class="container">
    <ul class="nav nav-tabs nav-justified" role="tablist">
        <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#upcoming">Upcoming Events (<%= @upcoming.count %>) </a>
        </li>
        <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#past">Past Events (<%= @past.count %>) </a>
        </li>
    </ul>


    <div class="tab-content">
        <div class="tab-pane container active" id="upcoming">
            <% if @upcoming.empty? %>
                <p> No upcoming events available </p>
            <% end %>
                <%= render 'shared/list', events: @upcoming %>
           
            
        </div>
        <div class="tab-pane container fade" id="past">
            <%= render 'shared/list', events: @past%> 

        </div>
    </div>
</div>     
<% end %>

<% else %>  
    <p> <i> Sign in to view events </i></p>
<% end %>

app/views/events/new.html.erb
<h5>Create an Event</h5>

<div class="row">
    <div class="col-lg-4">
        <%= form_for @event do |form| %>
            
            <%= form.label :title %>
            <%= form.text_field :title, class: 'form-control' %>

            <%= form.label :description %>
            <%= form.text_area :description, class: 'form-control' %>

            <%= form.label :date %>
            <%= form.date_field :date, class: "form-control" %>

            <%= form.submit "Add Event", class: "btn btn-primary" %>                
        <% end %>
    </div>
</div>

app/views/events/show.html.erb
<h3> Event detail </h3>

 <div class=" event media border p-3">
    <div class="media-body">
        <p class="creator a-white">
            <strong>Created By:</strong> <%= @event.creator.username %>
        </p>
        <p class="title">
            <strong>Title:</strong> <%= @event.title %>
        </p>
        <p class="description">
            <strong>Description:</strong> <%= @event.description %>
        </p>
        <p class="date">
            <strong>Date:</strong> <%= @event.date %>
        </p>
        <p class="timestamp">
            Created <%= time_ago_in_words(@event.created_at) %> ago.
        </p>
        <hr>

        <table class="attendees">
        <th> Attendees <%= @attendees.count %></th>
        <% @attendees.each do |attendee| %>
        <tr>
            <td><%= attendee.username %></td>
            <td><%= attendee.email %></td>
            <td><%= link_to 'See profile', attendee %></td>
        </tr>
        <% end %>
        <table>
        <hr>
        
        <%= link_to event_path(@event), class: "card-overlay", data: { confirm: "Move to : #{@event.title}?" } do %>
            <%= render 'shared/functions', event: @event %>
        <% end %>
    </div>
</div> 

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
<%= link_to "Happening", root_url, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
    <li class="nav-item"> <%= link_to "Home", root_path, :class => 'nav-link'%> </li>
    <% if logged_in? %>
        <li><%= link_to "Create Event", new_event_path, class: 'nav-link' %></li>
        <li> <%= link_to "Logout", logout_path, method: :delete, :class => 'nav-link'%></li>
    <% else %>
        <li class="nav-item pr-50"> <%= link_to "SignUp", signup_path, :class => 'nav-link'%></li>
        <li class="nav-item"> <%= link_to "Login", login_path, :class => 'nav-link btn btn-primary btn-sm text-white'%></li>
    <% end %>
    </ul>
    </div>
    
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Happening</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <div class="container top-container">
      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(object.errors.count, "error") %>.
        </div>
        <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_functions.html.erb
<% @event = event %>
<% @user = current_user %>

<% if @user &.creator_event? @event %>
  <%= link_to 'Delete', event_path(@event), method: :delete,
      data: { confirm: "You are about to delete this event. Are you sure?" },
      class: "action-btn" %>

<% elsif @user &.attended_event? @event %>
  <%= link_to 'Leave', attendances_path(event_id: @event.id), method: :delete,
      data: { confirm: "Leave this event?" },
      class: "action-btn" %>

<% elsif @event.upcoming? %>
  <%= link_to 'Attend', attendances_path(event_id: @event.id), method: :post,
      data: { confirm: "Attend this event?" },
      class: "action-btn" %>
      
<% end %>

app/views/shared/_list.html.erb
<% @events = events %>
<% if @events.any? %>
    <div class="events">
        <% @events.each do |event| %>
        <%= render event %>
        <% end %>
    </div>
    <%= will_paginate @events %>
<% end %>

app/views/users/new.html.erb
<h1>Users Signup</h1>

<div class="row">
    <div class="col-lg-4">
        <%= form_for(@user, url: signup_path) do |form| %>
            <%= render 'shared/error_messages', object: form.object %> 
            
            <%= form.label :username %>
            <%= form.text_field :username, class: 'form-control' %>

            <%= form.label :email %>
            <%= form.text_field :email, class: 'form-control' %>

            <%= form.submit "Signup", class: "btn btn-primary" %>                
        <% end %>

        <div class="text-center">
            <p class="mt-20">Already have one? <%= link_to 'Login now!', login_path%> </p>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<% if logged_in? %>
    <h2> <%= @user.username %> </h2><br>
    


    <ul class="nav nav-tabs nav-justified" role="tablist">
        <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#creators"> My Events (<%= @my_events.count %>) </a>
        </li>
        <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#attending">Attending Events (<%= @attended_events.count %>) </a>
        </li>
    </ul>


    <div class="tab-content detail-tabs">
        <div class="tab-pane container active" id="creators">
            <h6 class="mt-5"> Upcoming (<%= @my_events.upcoming.count %>): </h6><hr>
            <% if  @my_events.upcoming.empty? %>
                <p><i> <small>No upcoming events </small></i></p>
            <% end %>
            <%= render 'shared/list', events: @my_events.upcoming %>  

            <h6 class="pt-5"> Past (<%= @my_events.past.count %>): </h6><hr>
            <% if  @my_events.past.empty? %>
                <p><i> <small>No past expired events </small></i></p>
            <% end %>
            <%= render 'shared/list', events: @my_events.past %>          
        </div>
        <div class="tab-pane container fade" id="attending">
            <h6 class="mt-5"> Upcoming (<%= @attended_events.upcoming.count %>): </h6><hr>
            <% if  @attended_events.upcoming.empty? %>
                <p><i> <small>No upcoming attending events </small></i></p>
            <% end %>
            <%= render 'shared/list', events: @attended_events.upcoming %>  

            <h6 class="pt-5"> Past (<%= @attended_events.past.count %>): </h6><hr>
            <% if  @attended_events.past.empty? %>
                <p><i> <small>No past attended events </small></i></p>
            <% end %>
            <%= render 'shared/list', events: @attended_events.past %> 

        </div>
    </div>

<% else %>
    <%= link_to "Please login", "#"%>
<% end %>